# -*- coding: utf-8 -*-
"""visao_deep_learning_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i9-RFwMzdUdeDZoiNc8tD-deQJ0tEUJa

# Informações:
- Precisão de 67%
- Matriz de confusão com diagonal principal destacada
- ResNet34
- Fine tuning na melhor faixa de aprendizado identificada pelo lr_find()
- Gráfico lr_find()

Tentar: aplicar peso para que todas as classes tenham o mesmo impacto no treinamento e resolver problema de reprodutibilidade (toda vez que roda da um resultado diferente)

# Instruções

Para executar os códigos abaixo com mais rapidez:

1. Clique no ▾ do lado de "Conectar".

2. Alterar o tipo de ambiente de execução

3. Acelerador de hardware: GPU T4

# Importação e Visualização dos Dados

#1 - Download e extração dos dados
"""

# Baixa o arquivo zip direto do repositório do GitHub
!wget https://github.com/RaptorMaps/InfraredSolarModules/raw/master/2020-02-14_InfraredSolarModules.zip

# Extrai os arquivos silenciosamente (-q) para não poluir a tela
!unzip -q 2020-02-14_InfraredSolarModules.zip

# Mostra o que foi extraído na pasta atual
!ls

"""#2 - Leitura do JSON e criação do mapeamento"""

import json
import pandas as pd
import cv2
from matplotlib import pyplot as plt

# Abre e lê o arquivo JSON
with open('InfraredSolarModules/module_metadata.json', 'r') as f:
    metadados = json.load(f)

# Converte o JSON para um DataFrame do Pandas
df = pd.DataFrame.from_dict(metadados, orient='index')

# Consolidação de redundâncias
substituicoes = {
    'Cell-Multi': 'Cell',
    'Diode-Multi': 'Diode',
    'Hot-Spot-Multi': 'Hot-Spot'
}
df['anomaly_class'] = df['anomaly_class'].replace(substituicoes)

# Separa dataset em dois grupos
df_no_anomaly = df[df['anomaly_class'] == 'No-Anomaly']
df_anomalias = df[df['anomaly_class'] != 'No-Anomaly']

# Reduz classe 'No-Anomaly' para 1800 imagens
df_no_anomaly_reduzido = df_no_anomaly.sample(n=1800, random_state=42)

# Une os dois datasets e embaralha
df_balanceado = pd.concat([df_no_anomaly_reduzido, df_anomalias])
df_balanceado = df_balanceado.sample(frac=1, random_state=42).reset_index(drop=True)
df = df_balanceado

# Mostra as primeiras 5 linhas e a conagem das classes
print(df.head())
print("\n--- CONTAGEM DE CLASSES ---")
print(df['anomaly_class'].value_counts())

"""# Processamento de Imagens com Deep Learning

# 3 - Preparação dos Dados
"""

# Instala o fast.ai no ambiente do Colab
!pip install -U fastai -q
from fastai.vision.all import *
set_seed(42, reproducible=True)

# Cria os DataLoaders
dls = ImageDataLoaders.from_df(
    df,
    path='InfraredSolarModules',
    fn_col='image_filepath',
    label_col='anomaly_class',
    item_tfms=Resize(224),
    #batch_tfms=aug_transforms()  # Aplica rotações e brilho automáticos
    batch_tfms=aug_transforms(do_flip=True, max_rotate=0.0, max_lighting=0.0, max_warp=0.0)
)

# Exibe as imagens processadas
dls.show_batch()

"""# 4 - Treinamento"""

# Treinamento inicial com ResNet34
learn = vision_learner(dls, resnet34, metrics=accuracy)
learn.fit_one_cycle(4)

# Salva pesos
learn.save('modelo-resnet34-etapa1')

# Execura lr_find para encontrar a melhor faixa de aprendizado para o fine tuning
learn.unfreeze()
learn.lr_find()

# Treina na faixa de aprendizado selecionada do gráfico (fine tuning)
taxa_min = 1e-5
taxa_max = 1e-3

learn.load('modelo-resnet34-etapa1')

learn.unfreeze()
learn.fit_one_cycle(10, lr_max=slice(taxa_min, taxa_max))

# Mostra os resultados visuais: a classe verdadeira vs. a previsão do modelo
learn.show_results(max_n=9, figsize=(10, 10))

"""# 5 - Matriz de Confusão"""

interp = ClassificationInterpretation.from_learner(learn)

# Plota a matriz de confusão para as 4 classes
interp.plot_confusion_matrix(figsize=(7, 7))

"""# 6 - Top Losses
Diagnóstico visual de onde a rede errou estando convicta de que estava certa
"""

# Cria o objeto de interpretação
interp = ClassificationInterpretation.from_learner(learn)

# Plota as imagens com os maiores erros (Top Losses)
interp.plot_top_losses(k=9, figsize=(15, 11))

# Exporta o modelo final completo (arquitetura + pesos)
# Isso cria um arquivo 'modelo_termografico_final.pkl' que você pode usar depois para fazer inferências em tempo real ou num aplicativo.
learn.export('modelo_termografico_final.pkl')